services:
  eurojackpot-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  eurojackpot-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8080
      WDS_SOCKET_PORT: 0